version: "3.8"
services:
  sonarqube-custom:
    image: sonarqube:community
    container_name: sonarqube-custom
    ports:
      - "9000:9000"  #Se puede cambiar el puerto de destino es necesario para que no haya un conflicto de puertos
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - ci-network

  ngrok-sonarqube:
    image: ngrok/ngrok:latest
    container_name: ngrok-sonarqube
    networks:
      - ci-network
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - "8085:8085" #Se cambia el puerto por defecto para el contenedor de Ngrok del 8080 al 8085, para evitar comflictos con el contenedor de jenkins
    command: >
      start --all --config /etc/ngrok.yml

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:

networks:
  ci-network:

